on:
  push:
    paths:
      - AzureDevOps/CICDPipeline
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      run: |
        (cd /Udacity/AzureDevOps/CICDPipeline/ && make lint)
      
    - name: Test with pytest
      run: |
        (cd /Udacity/AzureDevOps/CICDPipeline/ && make test)
    


