on:
  push:
    paths:
      - AzureDevOps/CICDPipeline
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run make command
      run : make AzureDevOps/CICDPipeline/hello
    
