on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
        
    - name: Install dependencies
      run: |
        (cd /Udacity/AzureDevOps/CICDPipeline/ && make install)
        
    - name: Lint with pylint
      run: |
        (cd /Udacity/AzureDevOps/CICDPipeline/ && make lint)
      
    - name: Test with pytest
      run: |
        (cd /Udacity/AzureDevOps/CICDPipeline/ && make test)
    


